server:
  address: 0.0.0.0
  port: 8087

spring:
  security:
    user:
      name: dummy
      password: dummy
    basic:
      enabled: false
  application:
    name: schedule-service

  datasource:
    url: jdbc:mysql://dddd-db.c3cu28aqilh6.ap-southeast-1.rds.amazonaws.com:3306/dddd_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: admin
    password: shuaihaoshishabi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

jwt:
  secret: d3b0f9cce6c33f23a79fbd7dc08f4dc1f1f045a9e4d62c780f6b1e5a2b4c34d3

